devices(JSON.parse(File.read(ENV['DEVICES_JSON_PATH'] || 'devices.json')))
concurrent_simulators(true)
languages(["en-US"])
clear_previous_screenshots(true)
override_status_bar(true)
xcargs "-only-testing:IoTPanelsUITests/ScreenshotTests"
